/* global document, Office, msal, fetch, console, crypto */

Office.onReady((info) => {
  if (info.host === Office.HostType.Outlook) {
    document.getElementById("createListBtn").onclick = handleCreateList;
    document.getElementById("addEmailBtn").onclick = handleAddEmailOnly;
    document.getElementById("injectAndLog").onclick = handleInjectAndLog;
    document.getElementById("refreshTimezoneBtn").onclick = handleRefreshTimezone;
    
    // Auto-populate Generated By field
    if (Office.context.mailbox && Office.context.mailbox.userProfile) {
      document.getElementById("generatedBy").value = Office.context.mailbox.userProfile.emailAddress;
    }
    
    // Auto-calculate end time
    document.getElementById("startTime").addEventListener("change", calculateEndTime);
    document.getElementById("duration").addEventListener("input", calculateEndTime);

    // Tab Navigation Logic
    const radios = document.querySelectorAll('input[name="navMode"]');
    radios.forEach(radio => {
      radio.addEventListener('change', (e) => {
        if (e.target.value === 'edit') {
          document.getElementById('editMeetingSection').style.display = 'block';
          document.getElementById('injectAndLog').innerText = 'Update & Log';
        } else {
          document.getElementById('editMeetingSection').style.display = 'none';
          document.getElementById('injectAndLog').innerText = 'Schedule & Log';
        }
      });
    });

    // Email validation for multi-email fields
    const emailFields = document.querySelectorAll('.multi-email-input');
    emailFields.forEach(field => {
      field.addEventListener('blur', (e) => {
        formatAndValidateEmails(e.target);
      });
    });
    
    const leadEmailField = document.getElementById('leadEmail');
    if(leadEmailField) {
      leadEmailField.addEventListener('blur', (e) => {
        formatAndValidateEmails(e.target, true);
      });
    }
  }
});

function calculateEndTime() {
  const startTimeVal = document.getElementById("startTime").value;
  const durationVal = parseInt(document.getElementById("duration").value, 10);
  if (startTimeVal && durationVal) {
    const startDate = new Date(startTimeVal);
    const endDate = new Date(startDate.getTime() + durationVal * 60000);
    // format as YYYY-MM-DDTHH:mm:ss without Z
    const pad = (n) => n.toString().padStart(2, '0');
    const endStr = `${endDate.getFullYear()}-${pad(endDate.getMonth() + 1)}-${pad(endDate.getDate())}T${pad(endDate.getHours())}:${pad(endDate.getMinutes())}:00`;
    document.getElementById("endTime").value = endStr;
  }
}

function formatAndValidateEmails(element, singleOnly = false) {
  const rawValue = element.value;
  if (!rawValue.trim()) {
    element.classList.remove('error-border');
    element.parentElement.querySelector('.error-text').style.display = 'none';
    return;
  }

  // Split by comma, semicolon, space, newline
  const parts = rawValue.split(/[\s,;\n]+/).map(p => p.trim()).filter(p => p.length > 0);
  
  if (singleOnly && parts.length > 1) {
    element.classList.add('error-border');
    element.parentElement.querySelector('.error-text').innerText = "Only one email allowed here.";
    element.parentElement.querySelector('.error-text').style.display = 'block';
    return;
  }

  const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
  const invalidEmails = parts.filter(p => !emailRegex.test(p));

  if (invalidEmails.length > 0) {
    element.classList.add('error-border');
    element.parentElement.querySelector('.error-text').innerText = "Invalid emails found: " + invalidEmails.join(", ");
    element.parentElement.querySelector('.error-text').style.display = 'block';
  } else {
    element.classList.remove('error-border');
    element.parentElement.querySelector('.error-text').style.display = 'none';
    // Format output with semicolons
    element.value = parts.join(';');
  }
}

const siteId = "YOUR_SITE_ID"; // Replace with your SharePoint Site ID
const listId = "YOUR_LIST_ID"; // Replace with your SharePoint List ID
const clientId = "YOUR_ENTRA_CLIENT_ID"; // Replace with your Entra ID Client ID
const tenantId = "YOUR_TENANT_ID"; // Replace with your Tenant ID or 'common'

async function getAccessToken(scopes) {
  const msalConfig = {
    auth: {
      clientId: clientId,
      authority: `https://login.microsoftonline.com/${tenantId}`,
      redirectUri: "https://git-uvid.github.io/UVID-Teams-Meeting-Automate/taskpane.html",
    },
  };

  const msalInstance = new msal.PublicClientApplication(msalConfig);
  const loginRequest = { scopes: scopes };
  const loginResponse = await msalInstance.loginPopup(loginRequest);
  return loginResponse.accessToken;
}

function updateStatus(message, isError = false) {
  const statusEl = document.getElementById("statusMessage");
  statusEl.innerText = message;
  statusEl.style.color = isError ? "#d13438" : "#107c10";
}

// ==========================================
// TIMEZONE DROPDOWN
// ==========================================
async function handleRefreshTimezone() {
  updateStatus("Fetching Timezones from SharePoint...", false);
  try {
    const accessToken = await getAccessToken(["Sites.Read.All"]);
    const graphEndpoint = `https://graph.microsoft.com/v1.0/sites/${siteId}/lists/${listId}/columns/Timezone`;
    
    const response = await fetch(graphEndpoint, {
      method: "GET",
      headers: { Authorization: `Bearer ${accessToken}` }
    });

    if (!response.ok) {
      throw new Error("Failed to fetch column schema");
    }

    const columnData = await response.json();
    if (columnData.choice && columnData.choice.choices) {
      const selectEl = document.getElementById("timezone");
      selectEl.innerHTML = ""; // clear old options
      columnData.choice.choices.forEach(choiceVal => {
        const opt = document.createElement("option");
        opt.value = choiceVal;
        opt.innerText = choiceVal;
        selectEl.appendChild(opt);
      });
      updateStatus("Timezones updated successfully!", false);
    } else {
      updateStatus("Timezone column not found as a choice field.", true);
    }
  } catch (error) {
    updateStatus("Failed to update Timezones: " + error.message, true);
    console.error(error);
  }
}

// ==========================================
// BUTTON 1: Create List Only
// ==========================================
async function handleCreateList() {
  updateStatus("Authenticating for List Creation...", false);
  try {
    const accessToken = await getAccessToken(["Sites.Manage.All"]);
    updateStatus("Creating SharePoint List...", false);

    const graphEndpoint = `https://graph.microsoft.com/v1.0/sites/${siteId}/lists`;
    
    const listPayload = {
      displayName: "Meetings Log",
      columns: [
        { name: "MeetingID", text: {} },
        { name: "SeriesID", text: {} },
        { name: "Project", text: {} },
        { name: "MeetingType", choice: { choices: ["Client", "Internal"] } },
        { name: "LeadEmail", text: {} },
        { name: "Timezone", text: {} },
        { name: "Duration_x0028_minutes_x0029_", number: {} },
        { name: "Participants", text: {} },
        { name: "Recurring", boolean: {} },
        { name: "Status", choice: { choices: ["Scheduled", "Rescheduled", "Cancelled", "Completed"] } },
        { name: "MeetingStatus", choice: { choices: ["Requested", "Created", "Rescheduled", "Cancelled", "Completed"] } },
        { name: "GeneratedBy", text: {} },
        { name: "MeetingSubject", text: {} },
        { name: "MeetingEventmessagecontent", text: {} },
        { name: "Recurrencepattern", choice: { choices: ["Daily", "Monthly", "Weekly"] } },
        { name: "Recurrenceinterval", number: {} },
        { name: "Requiredattendees", text: {} },
        { name: "Optionalattendees", text: {} },
        { name: "Starttime", dateTime: {} },
        { name: "Endtime", dateTime: {} }
      ],
      list: {
        template: "genericList"
      }
    };

    const response = await fetch(graphEndpoint, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(listPayload),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error?.message || "List creation failed");
    }

    const createdList = await response.json();
    console.log("Created List ID:", createdList.id);
    updateStatus(`List created successfully! (ID: ${createdList.id})`, false);
  } catch (error) {
    updateStatus("Error: " + error.message, true);
    console.error(error);
  }
}

// ==========================================
// BUTTON 2: Add Email Only (Test)
// ==========================================
async function handleAddEmailOnly() {
  const leadEmail = document.getElementById("leadEmail").value;
  const title = document.getElementById("meetingTitle").value || "Test Meeting";

  if (!leadEmail) {
    updateStatus("Please enter a Lead Email first.", true);
    return;
  }

  updateStatus("Authenticating for Email Insertion...", false);
  try {
    const accessToken = await getAccessToken(["Sites.ReadWrite.All"]);
    updateStatus("Inserting test item...", false);

    const graphEndpoint = `https://graph.microsoft.com/v1.0/sites/${siteId}/lists/${listId}/items`;
    const payload = {
      fields: {
        Title: title,
        LeadEmail: leadEmail
      }
    };

    const response = await fetch(graphEndpoint, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error?.message || "Item creation failed");
    }

    updateStatus("Test email inserted successfully!", false);
  } catch (error) {
    updateStatus("Error: " + error.message, true);
    console.error(error);
  }
}

// ==========================================
// BUTTON 3: Schedule & Log (Full)
// ==========================================
async function handleInjectAndLog() {
  const isEditMode = document.querySelector('input[name="navMode"]:checked').value === 'edit';
  
  if (document.querySelectorAll('.error-border').length > 0) {
    updateStatus("Please fix email validation errors before submitting.", true);
    return;
  }

  const generateUUID = () => {
    if (typeof crypto.randomUUID === 'function') {
      return crypto.randomUUID();
    } else {
      return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
      });
    }
  };

  const generatedMeetingID = generateUUID();
  const generatedSeriesID = generateUUID();

  let startVal = document.getElementById("startTime").value;
  if (startVal && startVal.length === 16) {
    startVal += ":00";
  }

  // Capture all fields
  const fields = {
    Title: document.getElementById("meetingTitle").value,
    MeetingID: generatedMeetingID,
    SeriesID: generatedSeriesID,
    Project: document.getElementById("project").value,
    MeetingType: document.getElementById("meetingType").value,
    LeadEmail: document.getElementById("leadEmail").value,
    Starttime: startVal,
    Endtime: document.getElementById("endTime").value,
    Timezone: document.getElementById("timezone").value,
    Duration_x0028_minutes_x0029_: parseInt(document.getElementById("duration").value, 10) || null,
    Participants: document.getElementById("participants").value,
    Recurring: document.getElementById("recurring").checked,
    Status: document.getElementById("status").value,
    MeetingStatus: document.getElementById("meetingStatus").value,
    GeneratedBy: document.getElementById("generatedBy").value,
    MeetingSubject: document.getElementById("meetingSubject").value,
    MeetingEventmessagecontent: document.getElementById("meetingEventmessagecontent").value,
    Recurrencepattern: document.getElementById("recurrencePattern").value,
    Recurrenceinterval: parseInt(document.getElementById("recurrenceInterval").value, 10) || null,
    Requiredattendees: document.getElementById("requiredAttendees").value,
    Optionalattendees: document.getElementById("optionalAttendees").value
  };

  if (!fields.Title) {
    updateStatus("Meeting Title is required.", true);
    return;
  }
  
  // Clean up any nulls to avoid Graph API errors
  if (fields.Duration_x0028_minutes_x0029_ === null) delete fields.Duration_x0028_minutes_x0029_;
  if (fields.Recurrenceinterval === null) delete fields.Recurrenceinterval;

  // Inject into email body
  const template = `Subject: Schedule Meeting
Title: ${fields.Title}
Meeting ID: ${fields.MeetingID}
Date: ${fields.Starttime}
Timezone: ${fields.Timezone}
Duration: ${fields.Duration_x0028_minutes_x0029_ || ""} mins
Participants: ${fields.Participants}
Type: ${fields.MeetingType}
Status: ${fields.Status}`;

  updateStatus(isEditMode ? "Updating email..." : "Injecting into email...", false);
  Office.context.mailbox.item.body.setSelectedDataAsync(
    template,
    { coercionType: Office.CoercionType.Text },
    async (asyncResult) => {
      if (asyncResult.status === Office.AsyncResultStatus.Failed) {
        updateStatus("Failed to inject text: " + asyncResult.error.message, true);
        return;
      }

      try {
        updateStatus("Injected! Authenticating for full log...", false);
        const accessToken = await getAccessToken(["Sites.ReadWrite.All"]);
        updateStatus(isEditMode ? "Updating SharePoint item..." : "Logging to SharePoint...", false);

        // NOTE: In Edit Mode, you would typically use PATCH to update an existing item by ID.
        // For simplicity and since we don't have the item ID yet, we fallback to POST or you can extend handleFetchMeeting to store the ID.
        const graphEndpoint = `https://graph.microsoft.com/v1.0/sites/${siteId}/lists/${listId}/items`;
        const payload = { fields: fields };

        const response = await fetch(graphEndpoint, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify(payload),
        });

        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.error?.message || "Graph API request failed");
        }

        updateStatus(isEditMode ? "Successfully updated!" : "Successfully scheduled and logged!", false);
      } catch (error) {
        updateStatus("Error logging to SharePoint: " + error.message, true);
        console.error(error);
      }
    }
  );
}
